'use client';

import React from 'react';
import { Container } from '@/components/layout';
import { SectionReveal } from '@/components/ui';
import { useTranslation } from '@/lib/i18n';
import {
    HiOutlineShieldCheck,
    HiOutlineDatabase,
    HiOutlineExclamation,
    HiOutlineLockClosed,
    HiOutlineUserGroup,
    HiOutlineDocumentText,
    HiOutlineMail,
    HiOutlineInformationCircle,
} from 'react-icons/hi';

const EFFECTIVE_DATE = 'February 28, 2026';
const CONTACT_EMAIL = 'privacy@gitgov.io';

interface PolicySection {
    id: string;
    icon: React.ElementType;
    titleEn: string;
    titleEs: string;
    contentEn: React.ReactNode;
    contentEs: React.ReactNode;
}

export function PrivacyClient() {
    const { locale } = useTranslation();
    const isEs = locale === 'es';

    const sections: PolicySection[] = [
        {
            id: 'scope',
            icon: HiOutlineInformationCircle,
            titleEn: '1. Scope and Controller',
            titleEs: '1. Ámbito y Responsable del Tratamiento',
            contentEn: (
                <div className="space-y-3 text-gray-400 text-sm leading-relaxed">
                    <p>
                        This Privacy Policy applies to the <strong className="text-gray-200">GitGov Desktop</strong> application and the <strong className="text-gray-200">GitGov Control Plane</strong> server. It governs the collection, processing, and storage of operational metadata generated by developer workstations.
                    </p>
                    <p>
                        The <strong className="text-gray-200">data controller</strong> is the organization that deploys GitGov (your employer or the entity that licensed the software). GitGov (the software and its operators) acts as a <strong className="text-gray-200">data processor</strong> on behalf of the deploying organization.
                    </p>
                    <p>
                        Individual developers whose Git activity is monitored are <strong className="text-gray-200">data subjects</strong> under applicable data protection law (including GDPR where applicable).
                    </p>
                </div>
            ),
            contentEs: (
                <div className="space-y-3 text-gray-400 text-sm leading-relaxed">
                    <p>
                        Esta Política de Privacidad aplica a la aplicación <strong className="text-gray-200">GitGov Desktop</strong> y al servidor <strong className="text-gray-200">GitGov Control Plane</strong>. Regula la recogida, el tratamiento y el almacenamiento de metadatos operacionales generados en las estaciones de trabajo de los desarrolladores.
                    </p>
                    <p>
                        El <strong className="text-gray-200">responsable del tratamiento</strong> es la organización que despliega GitGov (tu empleador o la entidad que licenció el software). GitGov (el software y sus operadores) actúa como <strong className="text-gray-200">encargado del tratamiento</strong> en nombre de la organización desplegante.
                    </p>
                    <p>
                        Los desarrolladores cuya actividad Git es monitorizada son <strong className="text-gray-200">interesados</strong> en virtud de la legislación de protección de datos aplicable (incluyendo el RGPD cuando corresponda).
                    </p>
                </div>
            ),
        },
        {
            id: 'data-collected',
            icon: HiOutlineDatabase,
            titleEn: '2. Data Collected',
            titleEs: '2. Datos Recopilados',
            contentEn: (
                <div className="space-y-4 text-gray-400 text-sm leading-relaxed">
                    <p>GitGov captures <strong className="text-gray-200">operational metadata only</strong>. The following fields are collected per Git event:</p>
                    <div className="overflow-x-auto">
                        <table className="w-full text-xs border-collapse">
                            <thead>
                                <tr className="border-b border-white/10">
                                    <th className="text-left py-2 pr-4 text-gray-300 font-medium">Field</th>
                                    <th className="text-left py-2 pr-4 text-gray-300 font-medium">Example</th>
                                    <th className="text-left py-2 text-gray-300 font-medium">Purpose</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-white/[0.04]">
                                {[
                                    ['event_type', 'commit, push', 'Identifies the Git operation'],
                                    ['commit_sha', 'a3f8c2e…', 'Links event to a specific commit'],
                                    ['branch', 'feat/auth', 'Identifies target branch'],
                                    ['user_login', 'alice', 'Git author identifier'],
                                    ['timestamp', 'ISO 8601', 'When the operation occurred'],
                                    ['file_count', '12', 'Number of files staged (no names)'],
                                    ['repo_name', 'org/repo', 'Repository identifier'],
                                    ['client_version', '0.1.0', 'Desktop app version for compatibility'],
                                ].map(([field, example, purpose]) => (
                                    <tr key={field}>
                                        <td className="py-2 pr-4 font-mono text-brand-400">{field}</td>
                                        <td className="py-2 pr-4 text-gray-500">{example}</td>
                                        <td className="py-2 text-gray-500">{purpose}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                    <div className="bg-brand-500/10 border border-brand-500/20 rounded-lg p-4">
                        <p className="text-brand-300 font-medium text-xs mb-1">What is never collected</p>
                        <p className="text-gray-400 text-xs">Source code content, file contents, diff contents, commit messages longer than metadata, passwords, secrets, or any file data. No source code ever leaves the developer workstation.</p>
                    </div>
                </div>
            ),
            contentEs: (
                <div className="space-y-4 text-gray-400 text-sm leading-relaxed">
                    <p>GitGov captura <strong className="text-gray-200">únicamente metadatos operacionales</strong>. Los siguientes campos se recogen por evento Git:</p>
                    <div className="overflow-x-auto">
                        <table className="w-full text-xs border-collapse">
                            <thead>
                                <tr className="border-b border-white/10">
                                    <th className="text-left py-2 pr-4 text-gray-300 font-medium">Campo</th>
                                    <th className="text-left py-2 pr-4 text-gray-300 font-medium">Ejemplo</th>
                                    <th className="text-left py-2 text-gray-300 font-medium">Propósito</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-white/[0.04]">
                                {[
                                    ['event_type', 'commit, push', 'Identifica la operación Git'],
                                    ['commit_sha', 'a3f8c2e…', 'Enlaza el evento a un commit específico'],
                                    ['branch', 'feat/auth', 'Identifica la rama destino'],
                                    ['user_login', 'alice', 'Identificador del autor Git'],
                                    ['timestamp', 'ISO 8601', 'Cuándo ocurrió la operación'],
                                    ['file_count', '12', 'Número de archivos en stage (sin nombres)'],
                                    ['repo_name', 'org/repo', 'Identificador del repositorio'],
                                    ['client_version', '0.1.0', 'Versión de la app para compatibilidad'],
                                ].map(([field, example, purpose]) => (
                                    <tr key={field}>
                                        <td className="py-2 pr-4 font-mono text-brand-400">{field}</td>
                                        <td className="py-2 pr-4 text-gray-500">{example}</td>
                                        <td className="py-2 text-gray-500">{purpose}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                    <div className="bg-brand-500/10 border border-brand-500/20 rounded-lg p-4">
                        <p className="text-brand-300 font-medium text-xs mb-1">Qué nunca se recopila</p>
                        <p className="text-gray-400 text-xs">Contenido del código fuente, contenido de archivos, contenido de diffs, mensajes de commit más allá de metadatos, contraseñas, secretos ni datos de archivos. El código fuente nunca abandona la estación de trabajo del desarrollador.</p>
                    </div>
                </div>
            ),
        },
        {
            id: 'signals',
            icon: HiOutlineExclamation,
            titleEn: '3. Signals and Advisory Findings — Liability Limits',
            titleEs: '3. Señales y Hallazgos Consultivos — Límites de Responsabilidad',
            contentEn: (
                <div className="space-y-4 text-gray-400 text-sm leading-relaxed">
                    <p>
                        GitGov may generate <strong className="text-gray-200">non-compliance signals</strong> — automated observations that flag potential deviations from configured governance policies (e.g., a direct push to a protected branch, a commit outside configured working hours).
                    </p>
                    <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-4 space-y-2">
                        <p className="text-yellow-300 font-semibold text-xs uppercase tracking-wide">Important — Advisory Nature</p>
                        <ul className="text-gray-400 text-xs space-y-1.5 list-disc list-inside">
                            <li>Signals are <strong className="text-gray-200">computational observations</strong>, not legal conclusions, HR decisions, or determinations of misconduct.</li>
                            <li>A signal indicates that a configured policy rule may have been triggered. It does not establish intent, negligence, or fault.</li>
                            <li>Signals may contain <strong className="text-gray-200">false positives</strong> due to configuration errors, clock skew, or incomplete context available to the system.</li>
                            <li>GitGov provides no warranty — express or implied — as to the <strong className="text-gray-200">accuracy, completeness, or fitness</strong> of signals for any employment, disciplinary, or legal purpose.</li>
                            <li>The deploying organization assumes <strong className="text-gray-200">full responsibility</strong> for any decision made on the basis of a signal, including HR actions, performance reviews, or contractual enforcement.</li>
                        </ul>
                    </div>
                    <p>
                        GitGov operators expressly disclaim liability for damages arising from decisions made on the basis of signal data, including but not limited to wrongful termination claims, reputational harm, or regulatory action resulting from misuse of signal output.
                    </p>
                    <p>
                        Organizations deploying GitGov are responsible for ensuring their use of signal data complies with applicable labor law, employment contracts, works council agreements, and data protection regulations in their jurisdiction.
                    </p>
                </div>
            ),
            contentEs: (
                <div className="space-y-4 text-gray-400 text-sm leading-relaxed">
                    <p>
                        GitGov puede generar <strong className="text-gray-200">señales de incumplimiento</strong> — observaciones automatizadas que marcan posibles desviaciones de las políticas de gobernanza configuradas (p.ej., un push directo a una rama protegida, un commit fuera del horario laboral configurado).
                    </p>
                    <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-4 space-y-2">
                        <p className="text-yellow-300 font-semibold text-xs uppercase tracking-wide">Importante — Carácter Consultivo</p>
                        <ul className="text-gray-400 text-xs space-y-1.5 list-disc list-inside">
                            <li>Las señales son <strong className="text-gray-200">observaciones computacionales</strong>, no conclusiones jurídicas, decisiones de RRHH ni determinaciones de mala conducta.</li>
                            <li>Una señal indica que una regla de política configurada puede haberse activado. No establece intención, negligencia ni culpa.</li>
                            <li>Las señales pueden contener <strong className="text-gray-200">falsos positivos</strong> debido a errores de configuración, desfase de reloj o contexto incompleto disponible para el sistema.</li>
                            <li>GitGov no ofrece ninguna garantía — expresa o implícita — sobre la <strong className="text-gray-200">exactitud, integridad o idoneidad</strong> de las señales para ningún propósito laboral, disciplinario o legal.</li>
                            <li>La organización que despliega GitGov asume la <strong className="text-gray-200">responsabilidad plena</strong> de cualquier decisión tomada en base a una señal, incluyendo acciones de RRHH, evaluaciones de desempeño o ejecución contractual.</li>
                        </ul>
                    </div>
                    <p>
                        Los operadores de GitGov declinan expresamente toda responsabilidad por daños derivados de decisiones tomadas en base a datos de señales, incluyendo pero no limitado a reclamaciones por despido improcedente, daño reputacional o acción regulatoria resultante del uso indebido de las señales.
                    </p>
                    <p>
                        Las organizaciones que despliegan GitGov son responsables de garantizar que su uso de los datos de señales cumple con la legislación laboral aplicable, los contratos de trabajo, los acuerdos de comité de empresa y las normativas de protección de datos en su jurisdicción.
                    </p>
                </div>
            ),
        },
        {
            id: 'legal-basis',
            icon: HiOutlineDocumentText,
            titleEn: '4. Legal Basis for Processing',
            titleEs: '4. Base Jurídica del Tratamiento',
            contentEn: (
                <div className="space-y-3 text-gray-400 text-sm leading-relaxed">
                    <p>The deploying organization processes event metadata under one or more of the following legal bases:</p>
                    <ul className="space-y-2 list-none">
                        {[
                            ['Legitimate interests', 'Monitoring development operations for security, compliance, and traceability purposes constitutes a legitimate organizational interest under Art. 6(1)(f) GDPR, provided it is proportionate and employees are informed.'],
                            ['Legal obligation', 'Where applicable regulatory frameworks (SOC 2, ISO 27001, PCI-DSS) require demonstrable audit trails, processing may be necessary to comply with a legal obligation under Art. 6(1)(c) GDPR.'],
                            ['Contract performance', 'Where the developer\'s employment contract includes provisions for system activity monitoring, processing may be grounded in Art. 6(1)(b) GDPR.'],
                        ].map(([basis, desc]) => (
                            <li key={basis as string} className="flex gap-3">
                                <span className="mt-0.5 w-1.5 h-1.5 rounded-full bg-brand-400 flex-shrink-0 mt-2" />
                                <span><strong className="text-gray-300">{basis as string}:</strong> {desc as string}</span>
                            </li>
                        ))}
                    </ul>
                    <p className="text-xs text-gray-500 mt-2">
                        The deploying organization is responsible for establishing and documenting the applicable legal basis, notifying employees, and complying with any works council or collective bargaining requirements before deployment.
                    </p>
                </div>
            ),
            contentEs: (
                <div className="space-y-3 text-gray-400 text-sm leading-relaxed">
                    <p>La organización desplegante trata los metadatos de eventos bajo una o más de las siguientes bases jurídicas:</p>
                    <ul className="space-y-2 list-none">
                        {[
                            ['Intereses legítimos', 'La monitorización de las operaciones de desarrollo por razones de seguridad, cumplimiento y trazabilidad constituye un interés organizacional legítimo conforme al Art. 6(1)(f) RGPD, siempre que sea proporcionada y los empleados estén informados.'],
                            ['Obligación legal', 'Cuando los marcos regulatorios aplicables (SOC 2, ISO 27001, PCI-DSS) requieren pistas de auditoría demostrables, el tratamiento puede ser necesario para cumplir una obligación legal conforme al Art. 6(1)(c) RGPD.'],
                            ['Ejecución del contrato', 'Cuando el contrato de trabajo del desarrollador incluye disposiciones sobre monitorización de la actividad del sistema, el tratamiento puede fundamentarse en el Art. 6(1)(b) RGPD.'],
                        ].map(([basis, desc]) => (
                            <li key={basis as string} className="flex gap-3">
                                <span className="mt-0.5 w-1.5 h-1.5 rounded-full bg-brand-400 flex-shrink-0 mt-2" />
                                <span><strong className="text-gray-300">{basis as string}:</strong> {desc as string}</span>
                            </li>
                        ))}
                    </ul>
                    <p className="text-xs text-gray-500 mt-2">
                        La organización desplegante es responsable de establecer y documentar la base jurídica aplicable, informar a los empleados y cumplir con cualquier requisito de comité de empresa o convenio colectivo antes del despliegue.
                    </p>
                </div>
            ),
        },
        {
            id: 'retention',
            icon: HiOutlineLockClosed,
            titleEn: '5. Data Retention and Security',
            titleEs: '5. Retención de Datos y Seguridad',
            contentEn: (
                <div className="space-y-3 text-gray-400 text-sm leading-relaxed">
                    <p><strong className="text-gray-200">Retention:</strong> Event records are stored for the duration configured by the deploying organization. GitGov does not impose a maximum retention period; the deploying organization is responsible for defining and enforcing data minimization policies consistent with their legal obligations.</p>
                    <p><strong className="text-gray-200">Immutability:</strong> Audit event records are append-only. Records cannot be modified or deleted through the standard API. This design supports regulatory requirements for tamper-evident audit trails.</p>
                    <p><strong className="text-gray-200">Encryption in transit:</strong> All communication between GitGov Desktop and the Control Plane must be secured with TLS in production environments. HTTP is supported for local evaluation only.</p>
                    <p><strong className="text-gray-200">API key security:</strong> API keys are stored as SHA-256 hashes. The plain-text key is never persisted after initial issuance.</p>
                    <p><strong className="text-gray-200">Access control:</strong> The Control Plane enforces role-based access. Developers can only access their own event records. Administrative data is restricted to <code className="text-brand-400 text-xs bg-white/5 px-1 rounded">Admin</code>-role keys.</p>
                </div>
            ),
            contentEs: (
                <div className="space-y-3 text-gray-400 text-sm leading-relaxed">
                    <p><strong className="text-gray-200">Retención:</strong> Los registros de eventos se almacenan durante el periodo configurado por la organización desplegante. GitGov no impone un periodo máximo de retención; la organización es responsable de definir y aplicar políticas de minimización de datos acordes con sus obligaciones legales.</p>
                    <p><strong className="text-gray-200">Inmutabilidad:</strong> Los registros de eventos de auditoría son append-only. Los registros no pueden modificarse ni eliminarse a través de la API estándar. Este diseño apoya los requisitos regulatorios de pistas de auditoría a prueba de manipulaciones.</p>
                    <p><strong className="text-gray-200">Cifrado en tránsito:</strong> Toda comunicación entre GitGov Desktop y el Control Plane debe protegerse con TLS en entornos de producción. HTTP solo se admite para evaluación local.</p>
                    <p><strong className="text-gray-200">Seguridad de API keys:</strong> Las API keys se almacenan como hashes SHA-256. La clave en texto plano nunca se persiste después de su emisión inicial.</p>
                    <p><strong className="text-gray-200">Control de acceso:</strong> El Control Plane aplica control de acceso basado en roles. Los desarrolladores solo pueden acceder a sus propios registros de eventos. Los datos administrativos están restringidos a claves con rol <code className="text-brand-400 text-xs bg-white/5 px-1 rounded">Admin</code>.</p>
                </div>
            ),
        },
        {
            id: 'rights',
            icon: HiOutlineUserGroup,
            titleEn: '6. Data Subject Rights',
            titleEs: '6. Derechos de los Interesados',
            contentEn: (
                <div className="space-y-3 text-gray-400 text-sm leading-relaxed">
                    <p>Where GDPR or equivalent data protection law applies, individuals have the right to:</p>
                    <ul className="space-y-1.5 list-disc list-inside text-xs">
                        <li><strong className="text-gray-300">Access</strong> — Request a copy of event records associated with their user login.</li>
                        <li><strong className="text-gray-300">Rectification</strong> — Request correction of inaccurate metadata (e.g., incorrect user_login attribution).</li>
                        <li><strong className="text-gray-300">Erasure</strong> — Request deletion of event records, subject to the deploying organization&apos;s legal obligations to maintain audit trails.</li>
                        <li><strong className="text-gray-300">Restriction</strong> — Request that processing be restricted pending resolution of an accuracy dispute.</li>
                        <li><strong className="text-gray-300">Portability</strong> — Request event data in machine-readable format via the <code className="text-brand-400 bg-white/5 px-1 rounded">POST /export</code> endpoint.</li>
                        <li><strong className="text-gray-300">Objection</strong> — Object to processing based on legitimate interests grounds.</li>
                    </ul>
                    <p className="text-xs text-gray-500">
                        Requests should be directed to the deploying organization&apos;s Data Protection Officer or HR department. GitGov operators can only fulfill data requests upon written instruction from the deploying organization acting as data controller.
                    </p>
                </div>
            ),
            contentEs: (
                <div className="space-y-3 text-gray-400 text-sm leading-relaxed">
                    <p>Donde aplique el RGPD u otra legislación equivalente de protección de datos, los individuos tienen derecho a:</p>
                    <ul className="space-y-1.5 list-disc list-inside text-xs">
                        <li><strong className="text-gray-300">Acceso</strong> — Solicitar una copia de los registros de eventos asociados a su login de usuario.</li>
                        <li><strong className="text-gray-300">Rectificación</strong> — Solicitar la corrección de metadatos incorrectos (p.ej., atribución errónea de user_login).</li>
                        <li><strong className="text-gray-300">Supresión</strong> — Solicitar la eliminación de registros de eventos, sujeto a las obligaciones legales de la organización de mantener pistas de auditoría.</li>
                        <li><strong className="text-gray-300">Limitación</strong> — Solicitar la restricción del tratamiento mientras se resuelve una disputa de exactitud.</li>
                        <li><strong className="text-gray-300">Portabilidad</strong> — Solicitar los datos de eventos en formato legible por máquina a través del endpoint <code className="text-brand-400 bg-white/5 px-1 rounded">POST /export</code>.</li>
                        <li><strong className="text-gray-300">Oposición</strong> — Oponerse al tratamiento basado en la base de intereses legítimos.</li>
                    </ul>
                    <p className="text-xs text-gray-500">
                        Las solicitudes deben dirigirse al Delegado de Protección de Datos o al departamento de RRHH de la organización desplegante. Los operadores de GitGov solo pueden atender solicitudes de datos ante instrucción escrita de la organización desplegante en su calidad de responsable del tratamiento.
                    </p>
                </div>
            ),
        },
        {
            id: 'contact',
            icon: HiOutlineMail,
            titleEn: '7. Contact',
            titleEs: '7. Contacto',
            contentEn: (
                <div className="space-y-3 text-gray-400 text-sm leading-relaxed">
                    <p>For privacy-related inquiries regarding GitGov as software product, contact:</p>
                    <p>
                        <a href={`mailto:${CONTACT_EMAIL}`} className="text-brand-400 hover:text-brand-300 transition-colors">
                            {CONTACT_EMAIL}
                        </a>
                    </p>
                    <p className="text-xs text-gray-500">
                        For requests relating to your personal data held by your employer via GitGov, contact your organization directly. GitGov operators cannot act on individual data requests without authorization from the deploying organization.
                    </p>
                </div>
            ),
            contentEs: (
                <div className="space-y-3 text-gray-400 text-sm leading-relaxed">
                    <p>Para consultas de privacidad relacionadas con GitGov como producto software, contacta:</p>
                    <p>
                        <a href={`mailto:${CONTACT_EMAIL}`} className="text-brand-400 hover:text-brand-300 transition-colors">
                            {CONTACT_EMAIL}
                        </a>
                    </p>
                    <p className="text-xs text-gray-500">
                        Para solicitudes relacionadas con tus datos personales en posesión de tu empleador a través de GitGov, contacta directamente con tu organización. Los operadores de GitGov no pueden actuar sobre solicitudes individuales de datos sin autorización de la organización desplegante.
                    </p>
                </div>
            ),
        },
    ];

    return (
        <main className="min-h-screen bg-surface-400 py-20 md:py-28">
            <Container>
                <SectionReveal>
                    {/* Header */}
                    <div className="max-w-2xl mx-auto text-center mb-16">
                        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-brand-500/20 bg-brand-500/5 text-brand-400 text-xs font-medium tracking-wide uppercase mb-6">
                            <HiOutlineShieldCheck className="w-3.5 h-3.5" />
                            {isEs ? 'Legal' : 'Legal'}
                        </div>
                        <h1 className="text-3xl md:text-4xl font-bold text-white mb-4">
                            {isEs ? 'Política de Privacidad' : 'Privacy Policy'}
                        </h1>
                        <p className="text-gray-400 text-sm">
                            {isEs
                                ? `Vigente desde ${EFFECTIVE_DATE}. GitGov captura únicamente metadatos operacionales. El código fuente nunca abandona tu estación de trabajo.`
                                : `Effective ${EFFECTIVE_DATE}. GitGov captures operational metadata only. Source code never leaves your workstation.`}
                        </p>
                    </div>

                    {/* Key points strip */}
                    <div className="max-w-4xl mx-auto mb-14 grid grid-cols-1 sm:grid-cols-3 gap-4">
                        {(isEs ? [
                            ['Sin código fuente', 'Solo metadatos: SHA, rama, autor, timestamp, conteo de archivos.'],
                            ['Señales consultivas', 'Las señales son observaciones, no decisiones legales ni de RRHH.'],
                            ['La org controla los datos', 'Tu empleador es el responsable del tratamiento, no GitGov.'],
                        ] : [
                            ['No source code', 'Only metadata: SHA, branch, author, timestamp, file count.'],
                            ['Advisory signals', 'Signals are observations, not legal or HR determinations.'],
                            ['Org controls the data', 'Your employer is the data controller, not GitGov.'],
                        ]).map(([title, desc]) => (
                            <div key={title} className="bg-white/[0.03] border border-white/[0.06] rounded-xl p-4">
                                <p className="text-brand-400 font-semibold text-sm mb-1">{title}</p>
                                <p className="text-gray-500 text-xs leading-relaxed">{desc}</p>
                            </div>
                        ))}
                    </div>

                    {/* Sections */}
                    <div className="max-w-3xl mx-auto space-y-6">
                        {sections.map((section) => {
                            const Icon = section.icon;
                            return (
                                <div
                                    key={section.id}
                                    className="bg-white/[0.03] border border-white/[0.06] rounded-xl p-6"
                                >
                                    <div className="flex items-center gap-3 mb-4">
                                        <div className="w-8 h-8 rounded-lg bg-brand-500/10 border border-brand-500/20 flex items-center justify-center flex-shrink-0">
                                            <Icon className="w-4 h-4 text-brand-400" />
                                        </div>
                                        <h2 className="text-base font-semibold text-white">
                                            {isEs ? section.titleEs : section.titleEn}
                                        </h2>
                                    </div>
                                    {isEs ? section.contentEs : section.contentEn}
                                </div>
                            );
                        })}
                    </div>

                    {/* Bottom note */}
                    <div className="max-w-3xl mx-auto mt-8 text-center">
                        <p className="text-xs text-gray-600">
                            {isEs
                                ? 'Esta política puede actualizarse periódicamente. Los cambios materiales se comunicarán mediante la web de GitGov. El uso continuado de la plataforma tras la publicación de cambios implica la aceptación de la política revisada.'
                                : 'This policy may be updated periodically. Material changes will be communicated via the GitGov website. Continued use of the platform after changes are posted constitutes acceptance of the revised policy.'}
                        </p>
                    </div>
                </SectionReveal>
            </Container>
        </main>
    );
}
