const COMPLIANCE_PERIOD_REPORT_PDF_SCHEMA_VERSION: &str =
    "gitgov_period_compliance_report_pdf_export.v1";
const COMPLIANCE_PERIOD_REPORT_PDF_CONTENT_TYPE: &str = "application/pdf";

fn normalize_compliance_period_report_pdf_export_id(value: &str) -> Result<String, &'static str> {
    let normalized = value.trim().to_string();
    if normalized.starts_with("cprpdf_") && normalized.len() <= 80 {
        Ok(normalized)
    } else {
        Err("pdf_export_id must be a valid cprpdf_ identifier")
    }
}

fn normalize_compliance_period_report_pdf_request(
    payload: &mut CompliancePeriodReportPdfExportRequest,
) -> Result<(), Vec<String>> {
    normalize_release_approval_optional_text(&mut payload.org_name);
    Ok(())
}

fn normalize_compliance_period_report_pdf_query(
    query: &mut CompliancePeriodReportPdfExportQuery,
) -> Result<Option<String>, Vec<String>> {
    let mut errors = Vec::new();
    normalize_release_approval_optional_text(&mut query.org_name);
    let pdf_export_id = match query.pdf_export_id.take() {
        Some(value) if !value.trim().is_empty() => {
            match normalize_compliance_period_report_pdf_export_id(&value) {
                Ok(value) => Some(value),
                Err(error) => {
                    errors.push(error.to_string());
                    None
                }
            }
        }
        _ => None,
    };
    if errors.is_empty() {
        Ok(pdf_export_id)
    } else {
        Err(errors)
    }
}

fn compliance_period_report_pdf_response(
    pdf_export: CompliancePeriodReportPdfExportRecord,
) -> CompliancePeriodReportPdfExportResponse {
    CompliancePeriodReportPdfExportResponse {
        download_url: format!(
            "/compliance/period-reports/{}/pdf-export/download?pdf_export_id={}",
            pdf_export.period_report_id, pdf_export.pdf_export_id
        ),
        pdf_export,
    }
}

fn collect_compliance_period_report_pdf_lines(
    period_report: &CompliancePeriodReportRecord,
    artifact: &serde_json::Value,
    generated_by: &str,
    generated_at: i64,
) -> Vec<String> {
    let mut lines = Vec::new();
    lines.push("GitGov Period Compliance Report".to_string());
    lines.push(format!("Schema: {COMPLIANCE_PERIOD_REPORT_PDF_SCHEMA_VERSION}"));
    lines.push("Purpose: customer/auditor review artifact".to_string());
    lines.push(
        "Not a certification, compliance score, legal attestation, or official regulatory claim."
            .to_string(),
    );
    lines.push(String::new());
    push_wrapped_pdf_line(&mut lines, "Period report ID: ", &period_report.period_report_id);
    push_wrapped_pdf_line(
        &mut lines,
        "Framework filter: ",
        period_report.framework_id.as_deref().unwrap_or("all frameworks"),
    );
    push_wrapped_pdf_line(&mut lines, "Date range start: ", period_report.date_range_start);
    push_wrapped_pdf_line(&mut lines, "Date range end: ", period_report.date_range_end);
    push_wrapped_pdf_line(&mut lines, "Source report count: ", period_report.report_count);
    push_wrapped_pdf_line(&mut lines, "Generated by: ", generated_by);
    push_wrapped_pdf_line(&mut lines, "Generated at: ", generated_at);
    lines.push(String::new());
    lines.push("Source hashes".to_string());
    push_wrapped_pdf_line(
        &mut lines,
        "Source period report hash: ",
        &period_report.artifact_hash,
    );
    if let Some(hashes) = artifact.get("source_hashes") {
        if let Some(report_hashes) = hashes.get("report_hashes").and_then(|value| value.as_array())
        {
            push_wrapped_pdf_line(&mut lines, "Framework report hashes: ", report_hashes.len());
            for hash in report_hashes.iter().take(10) {
                push_wrapped_pdf_line(
                    &mut lines,
                    "- Report hash: ",
                    hash.as_str().unwrap_or("unknown"),
                );
            }
        }
        if let Some(manifest_hashes) =
            hashes.get("manifest_hashes").and_then(|value| value.as_array())
        {
            push_wrapped_pdf_line(&mut lines, "Manifest hashes: ", manifest_hashes.len());
            for hash in manifest_hashes.iter().take(10) {
                push_wrapped_pdf_line(
                    &mut lines,
                    "- Manifest hash: ",
                    hash.as_str().unwrap_or("unknown"),
                );
            }
        }
    }
    lines.push(String::new());
    lines.push("No-claim flags".to_string());
    push_wrapped_pdf_line(&mut lines, "compliance_claim=", period_report.compliance_claim);
    push_wrapped_pdf_line(&mut lines, "regulatory_claim=", period_report.regulatory_claim);
    push_wrapped_pdf_line(&mut lines, "certification=", period_report.certification);
    push_wrapped_pdf_line(
        &mut lines,
        "requires_auditor_review=",
        period_report.requires_auditor_review,
    );
    lines.push(String::new());
    lines.push("Period summary".to_string());
    if let Some(summary) = artifact.get("summary") {
        push_wrapped_pdf_line(&mut lines, "Summary: ", summary);
    }
    if let Some(missing) = artifact
        .get("missing_evidence_summary")
        .and_then(|value| value.as_array())
    {
        push_wrapped_pdf_line(&mut lines, "Missing evidence types: ", missing.len());
        for item in missing.iter().take(16) {
            let evidence_type = item
                .get("evidence_type")
                .and_then(|value| value.as_str())
                .unwrap_or("unknown");
            let report_count = item
                .get("report_count")
                .and_then(|value| value.as_i64())
                .unwrap_or(0);
            push_wrapped_pdf_line(
                &mut lines,
                "- Missing evidence: ",
                format!("{evidence_type} in {report_count} reports"),
            );
        }
    }
    if let Some(reports) = artifact.get("reports").and_then(|value| value.as_array()) {
        lines.push(String::new());
        lines.push("Source reports".to_string());
        for report in reports.iter().take(20) {
            let report_id = report
                .get("report_id")
                .and_then(|value| value.as_str())
                .unwrap_or("unknown");
            let framework = report
                .get("framework_id")
                .and_then(|value| value.as_str())
                .unwrap_or("unknown");
            let review_status = report
                .get("review_status")
                .and_then(|value| value.as_str())
                .unwrap_or("unknown");
            push_wrapped_pdf_line(
                &mut lines,
                "- Report: ",
                format!("{report_id} / {framework} / {review_status}"),
            );
        }
    }
    lines
}

fn deterministic_compliance_period_report_pdf_export_id(pdf_hash: &str) -> String {
    let suffix = pdf_hash.trim_start_matches("sha256:");
    format!("cprpdf_{}", &suffix[..32.min(suffix.len())])
}

pub async fn create_compliance_period_report_pdf_export(
    Extension(auth_user): Extension<AuthUser>,
    State(state): State<Arc<AppState>>,
    Path(period_report_id): Path<String>,
    Json(mut payload): Json<CompliancePeriodReportPdfExportRequest>,
) -> impl IntoResponse {
    if let Err(resp) = require_compliance_reviewer(&auth_user) {
        return resp.into_response();
    }
    let period_report_id = match normalize_compliance_period_report_id(&period_report_id) {
        Ok(value) => value,
        Err(error) => {
            return (StatusCode::BAD_REQUEST, Json(json!({ "error": error }))).into_response();
        }
    };
    if let Err(errors) = normalize_compliance_period_report_pdf_request(&mut payload) {
        return (
            StatusCode::BAD_REQUEST,
            Json(json!({ "error": "Invalid compliance period report PDF export request", "details": errors })),
        )
            .into_response();
    }
    let org_id = match resolve_compliance_framework_review_report_org(
        &state,
        &auth_user,
        payload.org_name.as_deref(),
    )
    .await
    {
        Ok(org_id) => org_id,
        Err(resp) => return resp,
    };

    let (period_report, artifact) = match state
        .db
        .get_compliance_period_report_with_payload(
            &org_id,
            &period_report_id,
            period_report_auditor_filter(&auth_user),
        )
        .await
    {
        Ok(Some(value)) => value,
        Ok(None) => {
            return (
                StatusCode::NOT_FOUND,
                Json(json!({ "error": "Compliance period report not found" })),
            )
                .into_response();
        }
        Err(e) => {
            tracing::error!(error = %e, org_id = %org_id, period_report_id = %period_report_id, "Failed to load period compliance report for PDF export");
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "Internal database error" })),
            )
                .into_response();
        }
    };
    if period_report.status != "generated" || period_report.format != "json" {
        return (
            StatusCode::CONFLICT,
            Json(json!({
                "error": "Period compliance report must be a generated JSON artifact before PDF export",
                "code": "period_report_not_generated"
            })),
        )
            .into_response();
    }
    if period_report.compliance_claim
        || period_report.regulatory_claim
        || period_report.certification
        || !period_report.requires_auditor_review
    {
        return (
            StatusCode::BAD_REQUEST,
            Json(json!({ "error": "Period compliance report claims are not eligible for PDF export" })),
        )
            .into_response();
    }

    let generated_at = chrono::Utc::now().timestamp_millis();
    let lines = collect_compliance_period_report_pdf_lines(
        &period_report,
        &artifact,
        &auth_user.client_id,
        generated_at,
    );
    let (pdf_bytes, page_count) = build_framework_review_report_pdf(&lines);
    let pdf_artifact_hash = framework_review_report_pdf_hash(&pdf_bytes);
    let pdf_export_id = deterministic_compliance_period_report_pdf_export_id(&pdf_artifact_hash);

    match state
        .db
        .create_compliance_period_report_pdf_export(
            &CreateCompliancePeriodReportPdfExportInput {
                pdf_export_id: &pdf_export_id,
                org_id: &org_id,
                period_report_id: &period_report.period_report_id,
                created_by_user_id: &auth_user.client_id,
                source_period_report_hash: &period_report.artifact_hash,
                pdf_artifact_hash: &pdf_artifact_hash,
                content_type: COMPLIANCE_PERIOD_REPORT_PDF_CONTENT_TYPE,
                page_count,
                pdf_bytes: &pdf_bytes,
            },
        )
        .await
    {
        Ok(pdf_export) => {
            let audit_entry = AdminAuditLogEntry {
                id: Uuid::new_v4().to_string(),
                actor_client_id: auth_user.client_id.clone(),
                action: "compliance_period_report.pdf_export_created".to_string(),
                target_type: Some("compliance_period_report".to_string()),
                target_id: Some(period_report.period_report_id.clone()),
                metadata: json!({
                    "org_id": org_id,
                    "period_report_id": period_report.period_report_id,
                    "pdf_export_id": pdf_export.pdf_export_id,
                    "source_period_report_hash": pdf_export.source_period_report_hash,
                    "pdf_artifact_hash": pdf_export.pdf_artifact_hash,
                    "content_type": pdf_export.content_type,
                    "page_count": pdf_export.page_count,
                    "compliance_claim": false,
                    "regulatory_claim": false,
                    "certification": false,
                    "agent_governance_required": false,
                    "source_period_report_artifact_mutated": false
                }),
                created_at: chrono::Utc::now().timestamp_millis(),
            };
            if let Err(e) = state.db.insert_admin_audit_log(&audit_entry).await {
                tracing::warn!("Failed to write period compliance report PDF export audit log: {}", e);
            }
            (
                StatusCode::CREATED,
                Json(compliance_period_report_pdf_response(pdf_export)),
            )
                .into_response()
        }
        Err(e) => {
            tracing::error!(error = %e, org_id = %org_id, period_report_id = %period_report_id, "Failed to create period compliance report PDF export");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "Internal database error" })),
            )
                .into_response()
        }
    }
}

pub async fn get_compliance_period_report_pdf_export(
    Extension(auth_user): Extension<AuthUser>,
    State(state): State<Arc<AppState>>,
    Path(period_report_id): Path<String>,
    Query(mut query): Query<CompliancePeriodReportPdfExportQuery>,
) -> impl IntoResponse {
    if let Err(resp) = require_compliance_reviewer(&auth_user) {
        return resp.into_response();
    }
    let period_report_id = match normalize_compliance_period_report_id(&period_report_id) {
        Ok(value) => value,
        Err(error) => {
            return (StatusCode::BAD_REQUEST, Json(json!({ "error": error }))).into_response();
        }
    };
    let pdf_export_id = match normalize_compliance_period_report_pdf_query(&mut query) {
        Ok(value) => value,
        Err(errors) => {
            return (
                StatusCode::BAD_REQUEST,
                Json(json!({ "error": "Invalid compliance period report PDF export query", "details": errors })),
            )
                .into_response();
        }
    };
    let org_id = match resolve_compliance_framework_review_report_org(
        &state,
        &auth_user,
        query.org_name.as_deref(),
    )
    .await
    {
        Ok(org_id) => org_id,
        Err(resp) => return resp,
    };
    match state
        .db
        .get_compliance_period_report(
            &org_id,
            &period_report_id,
            period_report_auditor_filter(&auth_user),
        )
        .await
    {
        Ok(Some(_)) => {}
        Ok(None) => {
            return (
                StatusCode::NOT_FOUND,
                Json(json!({ "error": "Compliance period report not found" })),
            )
                .into_response();
        }
        Err(e) => {
            tracing::error!(error = %e, org_id = %org_id, period_report_id = %period_report_id, "Failed to authorize period report PDF export lookup");
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "Internal database error" })),
            )
                .into_response();
        }
    }

    let result = match pdf_export_id.as_deref() {
        Some(pdf_export_id) => {
            state
                .db
                .get_compliance_period_report_pdf_export(&org_id, &period_report_id, pdf_export_id)
                .await
        }
        None => {
            state
                .db
                .get_latest_compliance_period_report_pdf_export(&org_id, &period_report_id)
                .await
        }
    };
    match result {
        Ok(Some(pdf_export)) => (
            StatusCode::OK,
            Json(compliance_period_report_pdf_response(pdf_export)),
        )
            .into_response(),
        Ok(None) => (
            StatusCode::NOT_FOUND,
            Json(json!({ "error": "Compliance period report PDF export not found" })),
        )
            .into_response(),
        Err(e) => {
            tracing::error!(error = %e, org_id = %org_id, period_report_id = %period_report_id, "Failed to load period compliance report PDF export");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "Internal database error" })),
            )
                .into_response()
        }
    }
}

pub async fn download_compliance_period_report_pdf_export(
    Extension(auth_user): Extension<AuthUser>,
    State(state): State<Arc<AppState>>,
    Path(period_report_id): Path<String>,
    Query(mut query): Query<CompliancePeriodReportPdfExportQuery>,
) -> impl IntoResponse {
    if let Err(resp) = require_compliance_reviewer(&auth_user) {
        return resp.into_response();
    }
    let period_report_id = match normalize_compliance_period_report_id(&period_report_id) {
        Ok(value) => value,
        Err(error) => {
            return (StatusCode::BAD_REQUEST, Json(json!({ "error": error }))).into_response();
        }
    };
    let pdf_export_id = match normalize_compliance_period_report_pdf_query(&mut query) {
        Ok(value) => value,
        Err(errors) => {
            return (
                StatusCode::BAD_REQUEST,
                Json(json!({ "error": "Invalid compliance period report PDF export download query", "details": errors })),
            )
                .into_response();
        }
    };
    let org_id = match resolve_compliance_framework_review_report_org(
        &state,
        &auth_user,
        query.org_name.as_deref(),
    )
    .await
    {
        Ok(org_id) => org_id,
        Err(resp) => return resp,
    };
    match state
        .db
        .get_compliance_period_report(
            &org_id,
            &period_report_id,
            period_report_auditor_filter(&auth_user),
        )
        .await
    {
        Ok(Some(_)) => {}
        Ok(None) => {
            return (
                StatusCode::NOT_FOUND,
                Json(json!({ "error": "Compliance period report not found" })),
            )
                .into_response();
        }
        Err(e) => {
            tracing::error!(error = %e, org_id = %org_id, period_report_id = %period_report_id, "Failed to authorize period report PDF export download");
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "Internal database error" })),
            )
                .into_response();
        }
    }

    match state
        .db
        .download_compliance_period_report_pdf_export(
            &org_id,
            &period_report_id,
            pdf_export_id.as_deref(),
        )
        .await
    {
        Ok(Some((pdf_export, bytes))) => {
            append_period_report_access_log(
                &state,
                PeriodReportAccessLogInput {
                    org_id: &org_id,
                    period_report_id: &period_report_id,
                    actor_client_id: &auth_user.client_id,
                    action: "downloaded_pdf",
                    artifact_type: "pdf",
                    artifact_id: Some(&pdf_export.pdf_export_id),
                    artifact_hash: Some(&pdf_export.pdf_artifact_hash),
                    metadata: json!({
                    "source_period_report_hash": pdf_export.source_period_report_hash.clone(),
                    "content_type": pdf_export.content_type.clone(),
                    "page_count": pdf_export.page_count,
                    "compliance_claim": false,
                    "regulatory_claim": false,
                    "certification": false,
                    "agent_governance_required": false
                    }),
                },
            )
            .await;
            let mut headers = HeaderMap::new();
            headers.insert(
                axum::http::header::CONTENT_TYPE,
                axum::http::HeaderValue::from_static(COMPLIANCE_PERIOD_REPORT_PDF_CONTENT_TYPE),
            );
            headers.insert(
                axum::http::header::CONTENT_DISPOSITION,
                axum::http::HeaderValue::from_str(&format!(
                    "attachment; filename=\"gitgov-period-compliance-{}.pdf\"",
                    pdf_export.pdf_export_id
                ))
                .unwrap_or_else(|_| axum::http::HeaderValue::from_static("attachment")),
            );
            headers.insert(
                axum::http::HeaderName::from_static("x-gitgov-artifact-hash"),
                axum::http::HeaderValue::from_str(&pdf_export.pdf_artifact_hash)
                    .unwrap_or_else(|_| axum::http::HeaderValue::from_static("invalid")),
            );
            (headers, Bytes::from(bytes)).into_response()
        }
        Ok(None) => (
            StatusCode::NOT_FOUND,
            Json(json!({ "error": "Compliance period report PDF export not found" })),
        )
            .into_response(),
        Err(e) => {
            tracing::error!(error = %e, org_id = %org_id, period_report_id = %period_report_id, "Failed to download period compliance report PDF export");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "Internal database error" })),
            )
                .into_response()
        }
    }
}
