import { detectBrowserTimezone, readStoredTimezone } from '@/lib/timezone'
import type { ControlPlaneState } from './types'
import {
  deriveActiveChatMessages,
  readStoredChatState,
  readStoredJiraCoverageFilters,
} from './helpers'

export function createInitialControlPlaneState(): ControlPlaneState {
  const initialChatState = readStoredChatState()
  return {
  serverConfig: null,
  serverStats: null,
  serverLogs: [],
  activeDevs7d: [],
  activeDevs7dUpdatedAt: null,
  logsPage: 0,
  logsPageSize: 10,
  jenkinsCorrelations: [],
  prMergeEvidence: [],
  dailyActivity: [],
  ticketCoverage: null,
  jiraCoverageFilters: readStoredJiraCoverageFilters(),
  jiraTicketDetails: {},
  jiraTicketDetailFetchedAt: {},
  jiraTicketDetailLoading: {},
  evidencePacket: null,
  evidencePacketTicketId: '',
  isEvidencePacketLoading: false,
  enterpriseAdoptionProfile: null,
  enterpriseAdoptionProfileUpdatedAt: null,
  isEnterpriseAdoptionProfileLoading: false,
  isEnterpriseAdoptionProfileSaving: false,
  enterpriseAdoptionProfileError: null,
  enterpriseOnboardingChecklistTracking: null,
  enterpriseOnboardingChecklistTrackingUpdatedAt: null,
  isEnterpriseOnboardingChecklistTrackingLoading: false,
  isEnterpriseOnboardingChecklistTrackingSaving: false,
  enterpriseOnboardingChecklistTrackingError: null,
  firstGovernedRepoSetup: null,
  firstGovernedRepoSetupUpdatedAt: null,
  isFirstGovernedRepoSetupLoading: false,
  isFirstGovernedRepoSetupSaving: false,
  firstGovernedRepoSetupError: null,
  releaseApprovals: [],
  releaseApprovalsTotal: 0,
  releaseApprovalsFilters: { limit: 10, offset: 0 },
  deploymentGateAuthorizations: [],
  deploymentGateAuthorizationsTotal: 0,
  deploymentGateAuthorizationsFilters: { limit: 10, offset: 0 },
  deploymentGateAuthorizationsUpdatedAt: null,
  complianceEvidenceSelectedDeploymentGateId: null,
  complianceControlFrameworks: [],
  complianceFrameworkPacks: [],
  selectedComplianceFrameworkId: 'gitgov_release_governance_baseline_v1',
  complianceFrameworkImportResponse: null,
  complianceFrameworkPackDiff: null,
  complianceEvidenceExport: null,
  complianceEvidenceMapping: null,
  complianceReviewPackage: null,
  complianceReviewPackageArtifact: null,
  complianceFrameworkReviewReport: null,
  complianceFrameworkReviewReports: null,
  assignedComplianceFrameworkReviewReports: null,
  complianceFrameworkReviewReportAssignments: null,
  complianceFrameworkReviewReportComments: null,
  complianceFrameworkReviewReportArtifact: null,
  complianceFrameworkReviewReportProvenanceManifest: null,
  complianceFrameworkReviewReportPdfExport: null,
  compliancePeriodReport: null,
  compliancePeriodReports: null,
  compliancePeriodReportArtifact: null,
  compliancePeriodReportAccessLog: null,
  compliancePeriodReportPdfExport: null,
  compliancePeriodReportProvenanceManifest: null,
  releaseGovernanceEvaluation: null,
  isReleaseGovernanceEvaluating: false,
  isReleaseApprovalsLoading: false,
  isDeploymentGateAuthorizationsLoading: false,
  isComplianceFrameworksLoading: false,
  isComplianceFrameworkPackImporting: false,
  isComplianceFrameworkPackReviewing: false,
  isComplianceFrameworkPackDiffLoading: false,
  isComplianceEvidenceExportCreating: false,
  isComplianceEvidenceMappingCreating: false,
  isComplianceReviewPackageCreating: false,
  isComplianceReviewPackageDownloading: false,
  isComplianceFrameworkReviewReportCreating: false,
  isComplianceFrameworkReviewReportsLoading: false,
  isAssignedComplianceFrameworkReviewReportsLoading: false,
  isComplianceFrameworkReviewReportAssignmentsLoading: false,
  isComplianceFrameworkReviewReportAssignmentsSaving: false,
  isComplianceFrameworkReviewReportCommentsLoading: false,
  isComplianceFrameworkReviewReportCommenting: false,
  isComplianceFrameworkReviewReportReviewing: false,
  isComplianceFrameworkReviewReportDownloading: false,
  isComplianceFrameworkReviewReportProvenanceManifestCreating: false,
  isComplianceFrameworkReviewReportPdfExportCreating: false,
  isComplianceFrameworkReviewReportPdfExportDownloading: false,
  isCompliancePeriodReportCreating: false,
  isCompliancePeriodReportsLoading: false,
  isCompliancePeriodReportDownloading: false,
  isCompliancePeriodReportReviewing: false,
  isCompliancePeriodReportRetentionUpdating: false,
  isCompliancePeriodReportAccessLogLoading: false,
  isCompliancePeriodReportPdfExportCreating: false,
  isCompliancePeriodReportPdfExportDownloading: false,
  isCompliancePeriodReportProvenanceManifestCreating: false,
  isCompliancePeriodReportProvenanceManifestDownloading: false,
  isReleaseApprovalSubmitting: false,
  releaseApprovalError: null,
  complianceEvidenceError: null,
  userRole: null,
  userClientId: null,
  userOrgId: null,
  controlPlaneAuthConfirmed: true,
  pendingControlPlaneSession: null,
  selectedOrgName: '',
  selectedOrgValidated: false,
  availableOrgs: [],
  isLoadingOrgs: false,
  orgUsers: [],
  orgUsersTotal: 0,
  orgInvitations: [],
  orgInvitationsTotal: 0,
  lastGeneratedInviteToken: null,
  teamOverview: [],
  teamOverviewTotal: 0,
  teamRepos: [],
  teamReposTotal: 0,
  teamWindowDays: 30,
  teamStatusFilter: '',
  apiKeys: [],
  isLoadingApiKeys: false,
  exportLogs: [],
  connectionStatus: 'disconnected',
  maintenanceDetectedAt: null,
  isConnected: false,
  isLoading: false,
  isRefreshingDashboard: false,
  error: null,
  chatSessions: initialChatState.sessions,
  activeChatSessionId: initialChatState.activeSessionId,
  chatMessages: deriveActiveChatMessages(initialChatState.sessions, initialChatState.activeSessionId),
  isChatLoading: false,
  governanceCopilotResponse: null,
  isGovernanceCopilotLoading: false,
  governanceCopilotError: null,
  displayTimezone: readStoredTimezone() || detectBrowserTimezone(),
  policyData: null,
  policyHistory: [],
  isPolicyLoading: false,
  isPolicySaving: false,
  policyError: null,
  sseConnected: false,
  }
}
