import {
  adoptionReadinessTarget,
  normalizeReleaseGovernancePolicy,
  releaseGovernanceGatePolicy,
  releaseGovernanceOverrideSummary,
  type EnterpriseAdoptionPack,
  type EnterpriseAdoptionProfile,
  type EnterpriseWorkflowTemplatePack,
} from './adoption-profile'
import { buildEnterpriseAdoptionPack } from './adoption-pack'

function yamlQuoted(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

function joinWorkflow(lines: string[]): string {
  return `${lines.join('\n')}\n`
}

function buildCiWorkflowTemplate(profile: EnterpriseAdoptionProfile): string {
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    '# Review project commands before installing in a customer repository.',
    'name: GitGov Customer CI',
    '',
    'on:',
    '  pull_request:',
    '  push:',
    `    branches: [${yamlQuoted(profile.default_branch.trim() || 'main')}]`,
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  ci:',
    '    name: Build and test',
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 30',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v6',
    '      - name: Setup Node.js',
    '        uses: actions/setup-node@v6',
    '        with:',
    '          node-version: 20',
    '      - name: Run detected checks',
    '        shell: pwsh',
    '        run: |',
    '          $ErrorActionPreference = "Stop"',
    '          if (Test-Path "package.json") {',
    '            if (Test-Path "package-lock.json") { npm ci } else { npm install }',
    '            npm run lint --if-present',
    '            npm run typecheck --if-present',
    '            npm test --if-present',
    '            npm run build --if-present',
    '          } else {',
    '            Write-Warning "Customize this CI template for the customer stack."',
    '          }',
  ])
}

function buildSecretScanWorkflowTemplate(profile: EnterpriseAdoptionProfile): string {
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    '# Baseline guard: block committed env/secret file paths.',
    'name: GitGov Secret And Publication Guard',
    '',
    'on:',
    '  pull_request:',
    '  push:',
    `    branches: [${yamlQuoted(profile.default_branch.trim() || 'main')}]`,
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  secret-publication-guard:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v6',
    '      - name: Block committed secret files',
    '        shell: pwsh',
    '        run: |',
    '          $ErrorActionPreference = "Stop"',
    '          $blocked = @(git ls-files | Where-Object { ($_ -match \'(^|/)\\.env($|\\.|/)\' -and $_ -notmatch \'\\.env\\.example$\') -or ($_ -match \'(^|/)secrets/\') })',
    '          if ($blocked.Count -gt 0) {',
    '            $blocked | ForEach-Object { Write-Host "Blocked: $_" }',
    '            throw "Secret-like files must not be committed."',
    '          }',
    '          Write-Host "PASS: no blocked secret file paths are tracked."',
  ])
}

function buildTraceabilityWorkflowTemplate(profile: EnterpriseAdoptionProfile): string {
  const jiraKey = profile.jira_project_key.trim() || 'KAN'
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    'name: GitGov Traceability Guard',
    '',
    'on:',
    '  pull_request:',
    '  push:',
    `    branches: [${yamlQuoted(profile.default_branch.trim() || 'main')}]`,
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  contents: read',
    '  pull-requests: read',
    '',
    'env:',
    `  JIRA_PROJECT_KEY: ${yamlQuoted(jiraKey)}`,
    '',
    'jobs:',
    '  traceability:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v6',
    '        with:',
    '          fetch-depth: 0',
    '      - name: Check branch, PR title, and latest commit',
    '        shell: pwsh',
    '        env:',
    '          EVENT_NAME_VALUE: ${{ github.event_name }}',
    '          HEAD_REF_VALUE: ${{ github.head_ref }}',
    '          REF_NAME_VALUE: ${{ github.ref_name }}',
    '          PR_TITLE_VALUE: ${{ github.event.pull_request.title }}',
    '        run: |',
    '          $ErrorActionPreference = "Stop"',
    '          $pattern = "\\b$([regex]::Escape($env:JIRA_PROJECT_KEY))-\\d+\\b"',
    '          $branch = if ([string]::IsNullOrWhiteSpace($env:HEAD_REF_VALUE)) { $env:REF_NAME_VALUE } else { $env:HEAD_REF_VALUE }',
    '          $commitSubject = git log -1 --pretty=%s',
    '          $failures = New-Object System.Collections.Generic.List[string]',
    '          if ($branch -notmatch $pattern) { $failures.Add("branch name") }',
    '          if ($env:EVENT_NAME_VALUE -eq "pull_request" -and $env:PR_TITLE_VALUE -notmatch $pattern) { $failures.Add("PR title") }',
    '          if ($commitSubject -notmatch $pattern) { $failures.Add("latest commit subject") }',
    '          if ($failures.Count -gt 0) { throw "Missing ticket ID pattern in: $($failures -join \', \')." }',
  ])
}

function buildGitGovEvidenceWorkflowTemplate(): string {
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    'name: GitGov Evidence Report',
    '',
    'on:',
    '  workflow_dispatch:',
    '  schedule:',
    '    - cron: "23 13 * * 1"',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  evidence-report:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Fetch GitGov stats',
    '        shell: pwsh',
    '        env:',
    '          GITGOV_URL: ${{ vars.GITGOV_URL }}',
    '          GITGOV_API_KEY: ${{ secrets.GITGOV_API_KEY }}',
    '          RUN_ID_VALUE: ${{ github.run_id }}',
    '        run: |',
    '          $ErrorActionPreference = "Stop"',
    '          New-Item -ItemType Directory -Force -Path "gitgov-evidence" | Out-Null',
    '          $outputPath = "gitgov-evidence/github-evidence-report-$env:RUN_ID_VALUE.json"',
    '          if ([string]::IsNullOrWhiteSpace($env:GITGOV_URL) -or [string]::IsNullOrWhiteSpace($env:GITGOV_API_KEY)) {',
    '            @{ status = "skipped"; reason = "missing_gitgov_config"; generated_at = [DateTimeOffset]::UtcNow.ToString("o") } | ConvertTo-Json | Out-File $outputPath -Encoding UTF8',
    '            exit 0',
    '          }',
    '          $headers = @{ Authorization = "Bearer $env:GITGOV_API_KEY" }',
    '          $stats = Invoke-RestMethod -Method GET -Uri "$($env:GITGOV_URL.TrimEnd(\'/\'))/stats" -Headers $headers',
    '          @{ status = "ok"; stats = $stats; generated_at = [DateTimeOffset]::UtcNow.ToString("o") } | ConvertTo-Json -Depth 12 | Out-File $outputPath -Encoding UTF8',
    '      - name: Upload evidence artifact',
    '        uses: actions/upload-artifact@v7',
    '        with:',
    '          name: github-evidence-report-${{ github.run_id }}',
    '          path: gitgov-evidence',
    '          if-no-files-found: error',
  ])
}

function buildArtifactMonitorWorkflowTemplate(name: string, artifactPrefix: string, outputPrefix: string): string {
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    `name: ${name}`,
    '',
    'on:',
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  actions: read',
    '  contents: read',
    '',
    'jobs:',
    '  artifact-monitor:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Check artifact freshness',
    '        shell: pwsh',
    '        env:',
    '          GH_TOKEN: ${{ github.token }}',
    '          REPOSITORY_NAME: ${{ github.repository }}',
    `          ARTIFACT_PREFIX: ${yamlQuoted(artifactPrefix)}`,
    `          OUTPUT_PREFIX: ${yamlQuoted(outputPrefix)}`,
    '        run: |',
    '          $ErrorActionPreference = "Stop"',
    '          New-Item -ItemType Directory -Force -Path "gitgov-evidence" | Out-Null',
    '          $headers = @{ Authorization = "Bearer $env:GH_TOKEN"; Accept = "application/vnd.github+json" }',
    '          $uri = "https://api.github.com/repos/$env:REPOSITORY_NAME/actions/artifacts?per_page=100"',
    '          $response = Invoke-RestMethod -Method GET -Uri $uri -Headers $headers',
    '          $latest = @($response.artifacts | Where-Object { $_.name -like "$env:ARTIFACT_PREFIX*" -and $_.expired -ne $true } | Sort-Object created_at -Descending | Select-Object -First 1)',
    '          $status = if ($latest.Count -gt 0) { "pass" } else { "fail" }',
    '          @{ status = $status; latest_artifact_name = if ($latest.Count) { $latest[0].name } else { $null }; generated_at = [DateTimeOffset]::UtcNow.ToString("o") } | ConvertTo-Json -Depth 8 | Out-File "gitgov-evidence/$env:OUTPUT_PREFIX.json" -Encoding UTF8',
    '          if ($status -ne "pass") { throw "No fresh evidence artifact found." }',
    '      - name: Upload monitor artifact',
    '        uses: actions/upload-artifact@v7',
    '        with:',
    `          name: ${outputPrefix}`,
    '          path: gitgov-evidence',
    '          if-no-files-found: error',
  ])
}

function buildArtifactTrendWorkflowTemplate(name: string, artifactPrefix: string, outputPrefix: string): string {
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    `name: ${name}`,
    '',
    'on:',
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  actions: read',
    '  contents: read',
    '',
    'jobs:',
    '  trend-report:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Build trend inventory',
    '        shell: pwsh',
    '        env:',
    '          GH_TOKEN: ${{ github.token }}',
    '          REPOSITORY_NAME: ${{ github.repository }}',
    `          ARTIFACT_PREFIX: ${yamlQuoted(artifactPrefix)}`,
    `          OUTPUT_PREFIX: ${yamlQuoted(outputPrefix)}`,
    '        run: |',
    '          $ErrorActionPreference = "Stop"',
    '          New-Item -ItemType Directory -Force -Path "gitgov-evidence" | Out-Null',
    '          $headers = @{ Authorization = "Bearer $env:GH_TOKEN"; Accept = "application/vnd.github+json" }',
    '          $uri = "https://api.github.com/repos/$env:REPOSITORY_NAME/actions/artifacts?per_page=100"',
    '          $response = Invoke-RestMethod -Method GET -Uri $uri -Headers $headers',
    '          $artifacts = @($response.artifacts | Where-Object { $_.name -like "$env:ARTIFACT_PREFIX*" } | Sort-Object created_at -Descending | Select-Object -First 10)',
    '          @{ status = if ($artifacts.Count) { "pass" } else { "missing" }; artifact_count = $artifacts.Count; generated_at = [DateTimeOffset]::UtcNow.ToString("o") } | ConvertTo-Json -Depth 8 | Out-File "gitgov-evidence/$env:OUTPUT_PREFIX.json" -Encoding UTF8',
    '          if ($artifacts.Count -eq 0) { throw "No artifacts found for prefix $env:ARTIFACT_PREFIX." }',
    '      - name: Upload trend artifact',
    '        uses: actions/upload-artifact@v7',
    '        with:',
    `          name: ${outputPrefix}`,
    '          path: gitgov-evidence',
    '          if-no-files-found: error',
  ])
}

function buildReleaseReadinessWorkflowTemplate(profile: EnterpriseAdoptionProfile): string {
  const target = adoptionReadinessTarget(profile.policy_preset)
  const enforce = profile.policy_preset === 'audit-only' ? 'false' : 'true'
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    'name: GitGov Release Readiness Gate',
    '',
    'on:',
    '  push:',
    `    branches: [${yamlQuoted(profile.default_branch.trim() || 'main')}]`,
    '  workflow_dispatch:',
    '    inputs:',
    '      enforce_gate:',
    '        description: "Fail when readiness is below target"',
    '        required: false',
    `        default: ${enforce}`,
    '        type: boolean',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  readiness:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Compute readiness',
    '        shell: pwsh',
    '        env:',
    '          GITGOV_URL: ${{ vars.GITGOV_URL }}',
    '          GITGOV_API_KEY: ${{ secrets.GITGOV_API_KEY }}',
    '          REPOSITORY_NAME: ${{ github.repository }}',
    '          REF_NAME_VALUE: ${{ github.ref_name }}',
    '          INPUT_ENFORCE_GATE: ${{ inputs.enforce_gate }}',
    `          TARGET_READINESS: ${yamlQuoted(String(target))}`,
    '        run: |',
    '          $ErrorActionPreference = "Stop"',
    '          if ([string]::IsNullOrWhiteSpace($env:GITGOV_URL) -or [string]::IsNullOrWhiteSpace($env:GITGOV_API_KEY)) { exit 0 }',
    '          $headers = @{ Authorization = "Bearer $env:GITGOV_API_KEY" }',
    '          $baseUrl = $env:GITGOV_URL.TrimEnd("/")',
    '          $repo = [Uri]::EscapeDataString($env:REPOSITORY_NAME)',
    '          $branch = [Uri]::EscapeDataString($env:REF_NAME_VALUE)',
    '          $coverage = Invoke-RestMethod -Method GET -Uri "$baseUrl/integrations/jira/ticket-coverage?repo_full_name=$repo&branch=$branch&hours=720" -Headers $headers',
    '          $score = [int]([double]($coverage.coverage_percentage ?? 0))',
    '          if ($score -lt [int]$env:TARGET_READINESS -and $env:INPUT_ENFORCE_GATE -eq "true") { throw "Readiness below target." }',
  ])
}

function buildReleaseGovernanceGateWorkflowTemplate(profile: EnterpriseAdoptionProfile): string {
  const releaseGovernance = normalizeReleaseGovernancePolicy(profile.release_governance)
  const gatePolicy = releaseGovernanceGatePolicy(releaseGovernance)
  const enforce = gatePolicy.mode === 'approval-required' || gatePolicy.mode === 'quorum-required'
    ? 'true'
    : 'false'
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    '# Manual release governance evaluation. Blocking is customer-selected, never default record-only behavior.',
    'name: GitGov Release Governance Gate',
    '',
    'on:',
    '  workflow_dispatch:',
    '    inputs:',
    '      org_name:',
    '        description: "GitGov organization scope"',
    '        required: false',
    '        default: ""',
    '        type: string',
    '      release_id:',
    '        description: "Release identifier to evaluate"',
    '        required: false',
    '        default: ""',
    '        type: string',
    '      environment:',
    '        description: "Release environment"',
    '        required: false',
    `        default: ${yamlQuoted(gatePolicy.environment)}`,
    '        type: string',
    '      evidence_packet_hash:',
    '        description: "Release-bound GitGov evidence packet SHA-256 hash"',
    '        required: false',
    '        default: ""',
    '        type: string',
    '      target_sha:',
    '        description: "Release target commit SHA; defaults to the workflow commit"',
    '        required: false',
    '        default: ""',
    '        type: string',
    '      enforce_gate:',
    '        description: "Fail only when explicitly blocking policy is not satisfied"',
    '        required: false',
    `        default: ${enforce}`,
    '        type: boolean',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  release-governance:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Evaluate release governance',
    '        shell: pwsh',
    '        env:',
    '          GITGOV_URL: ${{ vars.GITGOV_URL }}',
    '          GITGOV_API_KEY: ${{ secrets.GITGOV_API_KEY }}',
    '          REPOSITORY_NAME: ${{ github.repository }}',
    '          REF_NAME_VALUE: ${{ github.ref_name }}',
    '          SHA_VALUE: ${{ github.sha }}',
    '          RUN_ID_VALUE: ${{ github.run_id }}',
    '          ACTOR_VALUE: ${{ github.actor }}',
    '          INPUT_ORG_NAME: ${{ inputs.org_name }}',
    '          INPUT_RELEASE_ID: ${{ inputs.release_id }}',
    '          INPUT_ENVIRONMENT: ${{ inputs.environment }}',
    '          INPUT_EVIDENCE_PACKET_HASH: ${{ inputs.evidence_packet_hash }}',
    '          INPUT_TARGET_SHA: ${{ inputs.target_sha }}',
    '          INPUT_ENFORCE_GATE: ${{ inputs.enforce_gate }}',
    '        run: |',
    '          $ErrorActionPreference = "Stop"',
    '          New-Item -ItemType Directory -Force -Path "gitgov-evidence" | Out-Null',
    '          $outputPath = "gitgov-evidence/release-governance-gate-$env:RUN_ID_VALUE.json"',
    '          if ([string]::IsNullOrWhiteSpace($env:GITGOV_URL) -or [string]::IsNullOrWhiteSpace($env:GITGOV_API_KEY)) {',
    '            @{ status = "skipped"; reason = "missing_gitgov_url_or_api_key"; generated_at = [DateTimeOffset]::UtcNow.ToString("o") } | ConvertTo-Json -Depth 6 | Out-File -FilePath $outputPath -Encoding UTF8',
    '            if ($env:INPUT_ENFORCE_GATE -eq "true") { throw "Missing GitGov configuration for enforced release governance gate." }',
    '            exit 0',
    '          }',
    '          $releaseId = $env:INPUT_RELEASE_ID',
    '          if ([string]::IsNullOrWhiteSpace($releaseId)) { $releaseId = $env:REF_NAME_VALUE }',
    '          $environment = $env:INPUT_ENVIRONMENT',
    `          if ([string]::IsNullOrWhiteSpace($environment)) { $environment = ${yamlQuoted(gatePolicy.environment)} }`,
    '          $branch = $env:REF_NAME_VALUE',
    '          $targetSha = $env:INPUT_TARGET_SHA',
    '          if ([string]::IsNullOrWhiteSpace($targetSha)) { $targetSha = $env:SHA_VALUE }',
    '          if ([string]::IsNullOrWhiteSpace($env:INPUT_EVIDENCE_PACKET_HASH)) {',
    '            @{ status = "skipped"; reason = "missing_release_bound_evidence_packet_hash"; release_id = $releaseId; branch = $branch; target_sha = $targetSha; generated_at = [DateTimeOffset]::UtcNow.ToString("o") } | ConvertTo-Json -Depth 6 | Out-File -FilePath $outputPath -Encoding UTF8',
    '            if ($env:INPUT_ENFORCE_GATE -eq "true") { throw "Missing release-bound GitGov evidence packet hash for enforced release governance gate." }',
    '            exit 0',
    '          }',
    '          $payload = [ordered]@{',
    '            org_name = if ([string]::IsNullOrWhiteSpace($env:INPUT_ORG_NAME)) { $null } else { $env:INPUT_ORG_NAME }',
    '            release_id = $releaseId',
    '            repository_full_name = $env:REPOSITORY_NAME',
    '            branch = $branch',
    '            target_sha = $targetSha',
    '            environment = $environment',
    '            deployer = if ([string]::IsNullOrWhiteSpace($env:ACTOR_VALUE)) { "github-actions" } else { $env:ACTOR_VALUE }',
    '            ticket_id = $releaseId',
    '            evidence_packet_hash = $env:INPUT_EVIDENCE_PACKET_HASH',
    '            requested_by = "github-actions"',
    '            deployment_run_id = $env:RUN_ID_VALUE',
    '            metadata = @{ source = "gitgov-dashboard-generated-release-governance-gate"; workflow = "GitGov Release Governance Gate" }',
    '          }',
    '          $baseUrl = $env:GITGOV_URL.TrimEnd("/")',
    '          $headers = @{ Authorization = "Bearer $env:GITGOV_API_KEY"; Accept = "application/json"; "Content-Type" = "application/json" }',
    '          $authorization = Invoke-RestMethod -Method POST -Uri "$baseUrl/deployment-gates/authorize" -Headers $headers -Body ($payload | ConvertTo-Json -Depth 8)',
    '          $result = [ordered]@{ status = "authorized"; release_id = $releaseId; environment = $environment; enforce = ($env:INPUT_ENFORCE_GATE -eq "true"); authorization = @{ authorization_id = $authorization.authorization_id; decision = $authorization.decision; approved = $authorization.approved; blocking = $authorization.blocking; would_block = $authorization.would_block; reason = $authorization.reason; warnings = $authorization.warnings; blocked_by = $authorization.blocked_by; policy_checksum = $authorization.policy_checksum; break_glass_eligible = $authorization.break_glass_eligible; break_glass_used = $authorization.break_glass_used; break_glass_authorized_by = $authorization.break_glass_authorized_by }; evaluation = @{ status = $authorization.evaluation.status; policy_mode = $authorization.evaluation.policy.mode; policy_enforcement = $authorization.evaluation.policy.enforcement; policy_satisfied = $authorization.evaluation.policy_satisfied; blocking = $authorization.evaluation.blocking; would_block = $authorization.evaluation.would_block; valid_approval_count = $authorization.evaluation.valid_approval_count; required_approval_count = $authorization.evaluation.required_approval_count }; safety = @{ contains_secret_values = $false; prints_authorization_header = $false }; generated_at = [DateTimeOffset]::UtcNow.ToString("o") }',
    '          $result | ConvertTo-Json -Depth 10 | Out-File -FilePath $outputPath -Encoding UTF8',
    '          if ($env:INPUT_ENFORCE_GATE -eq "true" -and $authorization.blocking -eq $true) { throw "Release governance blocking policy is not satisfied." }',
    '      - name: Upload release governance evidence',
    '        uses: actions/upload-artifact@v7',
    '        with:',
    '          name: release-governance-gate-${{ github.run_id }}',
    '          path: gitgov-evidence',
    '          if-no-files-found: error',
  ])
}

function buildQualityGatePolicyWorkflowTemplate(profile: EnterpriseAdoptionProfile): string {
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    'name: GitGov Quality Gate Policy Matrix',
    '',
    'on:',
    '  pull_request:',
    '  push:',
    `    branches: [${yamlQuoted(profile.default_branch.trim() || 'main')}]`,
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  quality-gate-policy:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Emit policy evidence',
    '        shell: pwsh',
    '        env:',
    `          POLICY_PRESET: ${yamlQuoted(profile.policy_preset)}`,
    `          READINESS_TARGET: ${yamlQuoted(String(adoptionReadinessTarget(profile.policy_preset)))}`,
    '        run: |',
    '          $ErrorActionPreference = "Stop"',
    '          if ($env:POLICY_PRESET -notin @("audit-only", "moderate", "strict")) { throw "Unsupported policy preset." }',
    '          Write-Host "PASS: quality gate policy preset is valid."',
  ])
}

function buildSonarGovernanceWorkflowTemplate(): string {
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    'name: GitGov SonarQube Governance',
    '',
    'on:',
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  sonarqube-governance:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Check SonarQube quality gate',
    '        shell: pwsh',
    '        env:',
    '          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}',
    '          SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}',
    '          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}',
    '        run: |',
    '          $ErrorActionPreference = "Stop"',
    '          if ([string]::IsNullOrWhiteSpace($env:SONAR_HOST_URL) -or [string]::IsNullOrWhiteSpace($env:SONAR_PROJECT_KEY)) { exit 0 }',
    '          $headers = @{}',
    '          if (-not [string]::IsNullOrWhiteSpace($env:SONAR_TOKEN)) { $headers.Authorization = "Bearer $env:SONAR_TOKEN" }',
    '          $hostUrl = $env:SONAR_HOST_URL.TrimEnd("/")',
    '          Invoke-RestMethod -Method GET -Uri "$hostUrl/api/qualitygates/project_status?projectKey=$([Uri]::EscapeDataString($env:SONAR_PROJECT_KEY))" -Headers $headers | Out-Null',
  ])
}

function buildProductVulnerabilityReviewWorkflowTemplate(): string {
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    'name: GitGov Product Vulnerability Review',
    '',
    'on:',
    '  workflow_dispatch:',
    '  schedule:',
    '    - cron: "41 12 * * 4"',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  product-vulnerability-review:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v6',
    '      - name: Run dependency review baseline',
    '        shell: pwsh',
    '        run: |',
    '          $ErrorActionPreference = "Continue"',
    '          New-Item -ItemType Directory -Force -Path "gitgov-evidence/product-vulnerability-review" | Out-Null',
    '          if (Test-Path "package-lock.json") { npm audit --json | Out-File "gitgov-evidence/product-vulnerability-review/npm-audit.json" -Encoding UTF8 }',
    '          if (Test-Path "Cargo.lock") { cargo install cargo-audit --locked; cargo audit --json | Out-File "gitgov-evidence/product-vulnerability-review/cargo-audit.json" -Encoding UTF8 }',
    '      - name: Upload review evidence',
    '        uses: actions/upload-artifact@v7',
    '        with:',
    '          name: product-vulnerability-review-${{ github.run_id }}',
    '          path: gitgov-evidence/product-vulnerability-review',
    '          if-no-files-found: warn',
  ])
}

function buildVulnerabilityTrendEnforcementWorkflowTemplate(profile: EnterpriseAdoptionProfile): string {
  const baseline = profile.policy_preset === 'audit-only' ? '999' : '1'
  return joinWorkflow([
    '# Generated by GitGov dashboard workflow template pack.',
    'name: GitGov Vulnerability Trend Enforcement',
    '',
    'on:',
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  actions: read',
    '  contents: read',
    '',
    'jobs:',
    '  trend-enforcement:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Enforce latest review artifact presence',
    '        shell: pwsh',
    '        env:',
    '          GH_TOKEN: ${{ github.token }}',
    '          REPOSITORY_NAME: ${{ github.repository }}',
    '          ARTIFACT_PREFIX: "product-vulnerability-review-"',
    `          ACCEPTED_FINDING_BASELINE: ${yamlQuoted(baseline)}`,
    '        run: |',
    '          $ErrorActionPreference = "Stop"',
    '          $headers = @{ Authorization = "Bearer $env:GH_TOKEN"; Accept = "application/vnd.github+json" }',
    '          $uri = "https://api.github.com/repos/$env:REPOSITORY_NAME/actions/artifacts?per_page=100"',
    '          $response = Invoke-RestMethod -Method GET -Uri $uri -Headers $headers',
    '          $latest = @($response.artifacts | Where-Object { $_.name -like "$env:ARTIFACT_PREFIX*" -and $_.expired -ne $true } | Select-Object -First 1)',
    '          if ($latest.Count -eq 0) { throw "No fresh product vulnerability review artifact found." }',
  ])
}

function workflowTemplateContent(file: string, profile: EnterpriseAdoptionProfile): string {
  switch (file) {
    case '.github/workflows/ci.yml':
      return buildCiWorkflowTemplate(profile)
    case '.github/workflows/secret-scan.yml':
      return buildSecretScanWorkflowTemplate(profile)
    case '.github/workflows/public-naming-guard.yml':
      return buildTraceabilityWorkflowTemplate(profile)
    case '.github/workflows/github-evidence-report.yml':
      return buildGitGovEvidenceWorkflowTemplate()
    case '.github/workflows/github-evidence-artifact-monitor.yml':
      return buildArtifactMonitorWorkflowTemplate('GitGov Evidence Artifact Monitor', 'github-evidence-report-', 'github-evidence-artifact-monitor')
    case '.github/workflows/github-evidence-trend-report.yml':
      return buildArtifactTrendWorkflowTemplate('GitGov Evidence Trend Report', 'github-evidence-report-', 'github-evidence-trend-report')
    case '.github/workflows/release-readiness-gate.yml':
      return buildReleaseReadinessWorkflowTemplate(profile)
    case '.github/workflows/release-governance-gate.yml':
      return buildReleaseGovernanceGateWorkflowTemplate(profile)
    case '.github/workflows/release-governance-gate-artifact-monitor.yml':
      return buildArtifactMonitorWorkflowTemplate('GitGov Release Governance Gate Artifact Monitor', 'release-governance-gate-', 'release-governance-gate-artifact-monitor')
    case '.github/workflows/quality-gate-policy-matrix.yml':
      return buildQualityGatePolicyWorkflowTemplate(profile)
    case '.github/workflows/sonar-governance.yml':
      return buildSonarGovernanceWorkflowTemplate()
    case '.github/workflows/product-vulnerability-review.yml':
      return buildProductVulnerabilityReviewWorkflowTemplate()
    case '.github/workflows/product-vulnerability-review-artifact-monitor.yml':
      return buildArtifactMonitorWorkflowTemplate('GitGov Product Vulnerability Review Artifact Monitor', 'product-vulnerability-review-', 'product-vulnerability-review-artifact-monitor')
    case '.github/workflows/product-vulnerability-review-trend-report.yml':
      return buildArtifactTrendWorkflowTemplate('GitGov Product Vulnerability Review Trend Report', 'product-vulnerability-review-', 'product-vulnerability-review-trend-report')
    case '.github/workflows/product-vulnerability-review-trend-enforcement.yml':
      return buildVulnerabilityTrendEnforcementWorkflowTemplate(profile)
    default:
      return joinWorkflow([
        '# Generated by GitGov dashboard workflow template pack.',
        `name: ${file.split('/').pop()?.replace(/\.ya?ml$/, '') ?? 'GitGov workflow'}`,
        'on:',
        '  workflow_dispatch:',
        'permissions:',
        '  contents: read',
        'jobs:',
        '  placeholder:',
        '    runs-on: ubuntu-latest',
        '    steps:',
        '      - run: echo "Review and customize this generated workflow."',
      ])
  }
}

function buildWorkflowTemplateReadme(pack: EnterpriseAdoptionPack): string {
  const workflowLines = pack.workflow_plan.map((workflow) => `| \`${workflow.file}\` | ${workflow.reason.replace(/\|/g, '\\|')} |`)
  const variableLines = pack.variables.length > 0
    ? pack.variables.map((variable) => `| \`${variable.name}\` | ${variable.purpose.replace(/\|/g, '\\|')} | \`${variable.example}\` |`)
    : ['- None.']
  const secretLines = pack.secrets.length > 0
    ? pack.secrets.map((secret) => `| \`${secret.name}\` | ${secret.purpose.replace(/\|/g, '\\|')} | ${secret.value_policy.replace(/\|/g, '\\|')} |`)
    : ['- None.']
  const stepLines = pack.manual_steps.map((step) => `- **${step.step}:** ${step.detail}`)

  return [
    '# GitGov Workflow Template Pack',
    '',
    `Generated: \`${pack.generated_at}\``,
    '',
    `Customer: \`${pack.customer_name}\``,
    `Repository: \`${pack.repository_full_name}\``,
    `Default branch: \`${pack.default_branch}\``,
    `Policy preset: \`${pack.policy_preset}\``,
    `Release governance: \`${pack.release_governance.mode}\``,
    `Release enforcement: \`${pack.release_governance.enforcement}\``,
    `Release environment overrides: \`${releaseGovernanceOverrideSummary(pack.release_governance)}\``,
    pack.jira_project_key ? `Jira project key: \`${pack.jira_project_key}\`` : '',
    '',
    '## Generated Templates',
    '',
    '| Workflow | Why |',
    '|---|---|',
    ...workflowLines,
    '',
    '## Required Variables',
    '',
    ...(pack.variables.length > 0 ? ['| Name | Purpose | Example |', '|---|---|---|', ...variableLines] : variableLines),
    '',
    '## Required Secrets',
    '',
    ...(pack.secrets.length > 0 ? ['| Name | Purpose | Value Policy |', '|---|---|---|', ...secretLines] : secretLines),
    '',
    '## Manual Install Checklist',
    '',
    ...stepLines,
    '',
    '## Safety Notes',
    '',
    '- This pack contains workflow templates, variable names, and secret names only.',
    '- It does not contain secret values.',
    '- It does not mutate the customer repository automatically.',
    '- Review generated commands and permissions before copying templates into `.github/workflows`.',
  ].filter((line, index, lines) => line !== '' || lines[index - 1] !== '').join('\n')
}

export function buildEnterpriseWorkflowTemplatePack(
  profile: EnterpriseAdoptionProfile,
  generatedAt = new Date().toISOString(),
): EnterpriseWorkflowTemplatePack {
  const pack = buildEnterpriseAdoptionPack(profile, generatedAt)
  const files = pack.workflow_plan.map((workflow) => ({
    file: workflow.file,
    reason: workflow.reason,
    content: workflowTemplateContent(workflow.file, {
      ...profile,
      default_branch: pack.default_branch,
      jira_project_key: pack.jira_project_key,
      release_governance: pack.release_governance,
    }),
  }))

  return {
    generated_at: generatedAt,
    manifest: {
      generated_at: generatedAt,
      customer_name: pack.customer_name,
      repository_full_name: pack.repository_full_name,
      default_branch: pack.default_branch,
      jira_project_key: pack.jira_project_key,
      policy_preset: pack.policy_preset,
      release_governance: pack.release_governance,
      providers: pack.providers,
      modules: pack.modules,
      workflow_templates: files.map((file) => ({
        file: file.file,
        reason: file.reason,
        requires_review_before_install: true,
      })),
      variables: pack.variables,
      secrets: pack.secrets,
      manual_steps: [
        ...pack.manual_steps,
        {
          step: 'Review generated YAML',
          detail: 'Install templates only after customer owners review commands, schedules, permissions, and branch names.',
        },
        {
          step: 'Run workflow_dispatch first',
          detail: 'Validate each workflow manually before relying on schedules or blocking behavior.',
        },
      ],
      open_product_gaps: pack.open_product_gaps,
      safety: {
        contains_secret_values: false,
        mutates_customer_repository: false,
        requires_manual_install_review: true,
      },
    },
    files,
    readme: buildWorkflowTemplateReadme(pack),
  }
}
