// Split orchestrator for handler implementation files.
// Keep this file minimal to improve long-term maintainability.

include!("handlers/prelude_health.rs");
include!("handlers/integrations.rs");
include!("handlers/compliance_signals.rs");
include!("handlers/violations_policy_export.rs");
include!("handlers/github_webhook.rs");
include!("handlers/client_ingest_dashboard.rs");
include!("handlers/policy_admin.rs");
include!("handlers/policy_change_requests.rs");
include!("handlers/org_core.rs");
include!("handlers/platform_tenants.rs");
include!("handlers/org_users_api_keys.rs");
include!("handlers/adoption_profiles.rs");
include!("handlers/first_governed_repo_setup.rs");
include!("handlers/release_approvals.rs");
include!("handlers/governance_decisions.rs");
include!("handlers/deployment_gate_break_glass_approvals.rs");
include!("handlers/deployment_gates.rs");
include!("handlers/compliance_evidence_exports.rs");
include!("handlers/compliance_framework_packs.rs");
include!("handlers/compliance_evidence_mappings.rs");
include!("handlers/compliance_customer_framework_mapper.rs");
include!("handlers/compliance_review_packages.rs");
include!("handlers/compliance_framework_review_reports.rs");
include!("handlers/compliance_framework_review_report_collaboration.rs");
include!("handlers/agent_governance.rs");
include!("handlers/agent_governance_dry_run.rs");
include!("handlers/agent_governance_context.rs");
include!("handlers/agent_governance_admin.rs");
include!("handlers/agent_governance_agent_keys.rs");
#[cfg(test)]
include!("handlers/agent_governance_tests.rs");
#[cfg(test)]
include!("handlers/deployment_gate_tests.rs");
include!("handlers/audit_stream_governance.rs");
include!("handlers/jobs_merges_admin_audit.rs");
include!("handlers/gdpr_clients_identities_scope.rs");
include!("handlers/conversational_runtime.rs");
include!("handlers/chat_handler.rs");
include!("handlers/feature_requests.rs");
include!("handlers/sse.rs");
include!("handlers/metrics_endpoint.rs");
include!("handlers/cli_audit.rs");
include!("handlers/policy_drift_audit.rs");
include!("handlers/tests.rs");
